### ISSUE TITLE
Mapping error with special types using QLRM JpaResultMapper

### ISSUE THREAD

**Issue by aciapetti** [72services/qlrm#29] opened 2022-11-21 17:46 UTC
I have a PostrgreSQL database, with a field of type UUID (Postgres special type).
My entity mapping, based on Spring Data JPA and Hibernate Types, is defined like this:

`@Id
@Column(name = "id", nullable = false)
@Type(type="org.hibernate.type.PostgresUUIDType")
private UUID id;`

I'd like to define a native query with this field, and other two String fields.

I've tried to include the same field in a projection bean, mapped to the query results with the QLRM JpaResultMapper.
Even annotating the bean field with the org.hibernate.annotations.Type annotation, as defined in the entity,I still receive an error in the preparation of query results:

org.springframework.orm.jpa.JpaSystemException: No Dialect mapping for JDBC type: 1111; 
nested exception is org.hibernate.MappingException: No Dialect mapping for JDBC type: 1111

Is it possible that the library will be able to recognize these "special" fields? 
Any workaround suggested?

Thanks a lot.

    -Andrea

![Schermata da 2022-11-21 18-45-05](https://user-images.githubusercontent.com/704205/203124606-1a95101e-5053-4ba0-8d8d-cbf8653cae04.png)

**Comment by simasch** [comment] 2022-11-21 20:09
What's the type of the attribute in the POJO you are trying to map to?
It would be very helpful if you could provide a reproducible example or at least the minimal code necessary to reproduce the problem

**Comment by aciapetti** [comment] 2022-11-22 12:45
Hi @simasch, the type used is simply **java.util.UUID**.
This type is a PostgreSQL extension, but can be used in Spring Data JPA / Hibernate using the new annotation:
`@Type(type="org.hibernate.type.PostgresUUIDType")`

In order to provide a very simple reproducible example, I have created a public [Github repository](https://github.com/aciapetti/qlrm_sample) for putting the code in a single place. Let me know if you think it's enough.

Just create the PostgreSQL DB (version 12.x or later) with the SQL scripts included in src/main/resources and execute the Spring Boot application with the configured runner to reproduce the error.

**Comment by simasch** [comment] 2022-11-22 13:08
Thank you for the sample project.
The JpaResultMapper only uses JPA and JDBC standard functionality and does not consider any type of mapping.

The easiest way to solve your problem is to use the UUID as String.
To do that you have to cast it in the query:

    public static final String SELECT_ALL_BASE_INVESTIGATIONS_INFO_DECRYPTED = 
		"select  CAST(id as varchar) id, pgp_sym_decrypt(name, '%s') as decryptedName, pgp_sym_decrypt(description, '%s') as decryptedDescription from investigations";

And the DTO must use String as well:

```
public class InvestigationBaseDecryptedInfoProjection implements Serializable {
	
	private String id;
	private String decryptedName;
	private String decryptedDescription;
}
```

I'm closing the issue because there are no plans to support type mapping.

**Closed by simasch** 2022-11-22 13:08 UTC

**Comment by aciapetti** [comment] 2022-11-22 13:27
Thanks, @simasch, the workaround using CAST(id as varchar) works very well.

**Comment by simasch** [comment] 2022-11-22 13:28
That's good to hear. 👍
